[package]
name = "rsh"
version = "0.1.0"
authors = ["Codecrafters <hello@codecrafters.io>"]
edition = "2021"
rust-version = "1.80"

[dependencies]
regex = "1.11.1"

[dev-dependencies]
rstest = "0.24.0"
